# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyFTPD_GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(746, 475)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/file-server-300px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 741, 421))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.sIp = QtGui.QLineEdit(self.tab_2)
        self.sIp.setGeometry(QtCore.QRect(110, 10, 113, 21))
        self.sIp.setObjectName(_fromUtf8("sIp"))
        self.sPort = QtGui.QLineEdit(self.tab_2)
        self.sPort.setGeometry(QtCore.QRect(110, 40, 113, 21))
        self.sPort.setObjectName(_fromUtf8("sPort"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 91, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.rdbNormal = QtGui.QRadioButton(self.tab_2)
        self.rdbNormal.setGeometry(QtCore.QRect(10, 70, 100, 22))
        self.rdbNormal.setObjectName(_fromUtf8("rdbNormal"))
        self.rdbThreaded = QtGui.QRadioButton(self.tab_2)
        self.rdbThreaded.setGeometry(QtCore.QRect(120, 70, 100, 22))
        self.rdbThreaded.setObjectName(_fromUtf8("rdbThreaded"))
        self.rdbMultiprocess = QtGui.QRadioButton(self.tab_2)
        self.rdbMultiprocess.setGeometry(QtCore.QRect(220, 70, 100, 22))
        self.rdbMultiprocess.setObjectName(_fromUtf8("rdbMultiprocess"))
        self.sMaximumConnections = QtGui.QLineEdit(self.tab_2)
        self.sMaximumConnections.setGeometry(QtCore.QRect(150, 100, 113, 21))
        self.sMaximumConnections.setObjectName(_fromUtf8("sMaximumConnections"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 100, 141, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.sMaximumConnectionsPerIp = QtGui.QLineEdit(self.tab_2)
        self.sMaximumConnectionsPerIp.setGeometry(QtCore.QRect(180, 130, 113, 21))
        self.sMaximumConnectionsPerIp.setObjectName(_fromUtf8("sMaximumConnectionsPerIp"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(10, 130, 171, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.rdbFTP = QtGui.QRadioButton(self.tab)
        self.rdbFTP.setGeometry(QtCore.QRect(20, 30, 51, 22))
        self.rdbFTP.setObjectName(_fromUtf8("rdbFTP"))
        self.rdbThrottled = QtGui.QRadioButton(self.tab)
        self.rdbThrottled.setGeometry(QtCore.QRect(70, 30, 81, 22))
        self.rdbThrottled.setObjectName(_fromUtf8("rdbThrottled"))
        self.rdbDTP = QtGui.QRadioButton(self.tab)
        self.rdbDTP.setGeometry(QtCore.QRect(160, 30, 51, 22))
        self.rdbDTP.setObjectName(_fromUtf8("rdbDTP"))
        self.rdbTLS = QtGui.QRadioButton(self.tab)
        self.rdbTLS.setGeometry(QtCore.QRect(220, 30, 51, 22))
        self.rdbTLS.setObjectName(_fromUtf8("rdbTLS"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 70, 721, 291))
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.sFTPTimeout = QtGui.QLineEdit(self.tab_3)
        self.sFTPTimeout.setGeometry(QtCore.QRect(110, 10, 113, 21))
        self.sFTPTimeout.setObjectName(_fromUtf8("sFTPTimeout"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 151, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.sMaxLoginAtempts = QtGui.QLineEdit(self.tab_3)
        self.sMaxLoginAtempts.setGeometry(QtCore.QRect(170, 40, 113, 21))
        self.sMaxLoginAtempts.setObjectName(_fromUtf8("sMaxLoginAtempts"))
        self.chkPermitForeignAddresses = QtGui.QCheckBox(self.tab_3)
        self.chkPermitForeignAddresses.setGeometry(QtCore.QRect(520, 10, 171, 22))
        self.chkPermitForeignAddresses.setObjectName(_fromUtf8("chkPermitForeignAddresses"))
        self.chkPermitPrivilegedPorts = QtGui.QCheckBox(self.tab_3)
        self.chkPermitPrivilegedPorts.setGeometry(QtCore.QRect(520, 40, 161, 22))
        self.chkPermitPrivilegedPorts.setObjectName(_fromUtf8("chkPermitPrivilegedPorts"))
        self.sMasqueradeAddress = QtGui.QLineEdit(self.tab_3)
        self.sMasqueradeAddress.setGeometry(QtCore.QRect(170, 70, 113, 21))
        self.sMasqueradeAddress.setObjectName(_fromUtf8("sMasqueradeAddress"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 151, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 41, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.sStart = QtGui.QLineEdit(self.tab_3)
        self.sStart.setGeometry(QtCore.QRect(40, 140, 113, 21))
        self.sStart.setObjectName(_fromUtf8("sStart"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 41, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.sStop = QtGui.QLineEdit(self.tab_3)
        self.sStop.setGeometry(QtCore.QRect(40, 160, 113, 21))
        self.sStop.setObjectName(_fromUtf8("sStop"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 141, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.chkUseGMTTimes = QtGui.QCheckBox(self.tab_3)
        self.chkUseGMTTimes.setGeometry(QtCore.QRect(520, 70, 151, 22))
        self.chkUseGMTTimes.setObjectName(_fromUtf8("chkUseGMTTimes"))
        self.chkTCPNoDelay = QtGui.QCheckBox(self.tab_3)
        self.chkTCPNoDelay.setGeometry(QtCore.QRect(520, 100, 101, 22))
        self.chkTCPNoDelay.setObjectName(_fromUtf8("chkTCPNoDelay"))
        self.chkUseSendFile = QtGui.QCheckBox(self.tab_3)
        self.chkUseSendFile.setGeometry(QtCore.QRect(520, 130, 101, 22))
        self.chkUseSendFile.setObjectName(_fromUtf8("chkUseSendFile"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 220, 121, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.sAuthFailedTimeout = QtGui.QLineEdit(self.tab_3)
        self.sAuthFailedTimeout.setGeometry(QtCore.QRect(130, 220, 113, 21))
        self.sAuthFailedTimeout.setObjectName(_fromUtf8("sAuthFailedTimeout"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(10, 190, 41, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.sBanner = QtGui.QLineEdit(self.tab_3)
        self.sBanner.setGeometry(QtCore.QRect(60, 190, 221, 21))
        self.sBanner.setObjectName(_fromUtf8("sBanner"))
        self.label_34 = QtGui.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(230, 10, 21, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.sReadLimit = QtGui.QLineEdit(self.tab_4)
        self.sReadLimit.setGeometry(QtCore.QRect(110, 10, 113, 21))
        self.sReadLimit.setObjectName(_fromUtf8("sReadLimit"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sWriteLimit = QtGui.QLineEdit(self.tab_4)
        self.sWriteLimit.setGeometry(QtCore.QRect(110, 40, 113, 21))
        self.sWriteLimit.setObjectName(_fromUtf8("sWriteLimit"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(230, 10, 56, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(230, 40, 56, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.sDTPTimeout = QtGui.QLineEdit(self.tab_5)
        self.sDTPTimeout.setGeometry(QtCore.QRect(110, 10, 113, 21))
        self.sDTPTimeout.setObjectName(_fromUtf8("sDTPTimeout"))
        self.sInBufferSize = QtGui.QLineEdit(self.tab_5)
        self.sInBufferSize.setGeometry(QtCore.QRect(110, 40, 113, 21))
        self.sInBufferSize.setObjectName(_fromUtf8("sInBufferSize"))
        self.label_4 = QtGui.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.sOutBufferSize = QtGui.QLineEdit(self.tab_5)
        self.sOutBufferSize.setGeometry(QtCore.QRect(110, 70, 113, 21))
        self.sOutBufferSize.setObjectName(_fromUtf8("sOutBufferSize"))
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_23 = QtGui.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(230, 40, 56, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(230, 70, 56, 17))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(230, 10, 56, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.sCertificate = QtGui.QLineEdit(self.tab_6)
        self.sCertificate.setGeometry(QtCore.QRect(70, 10, 261, 21))
        self.sCertificate.setObjectName(_fromUtf8("sCertificate"))
        self.label = QtGui.QLabel(self.tab_6)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.sKey = QtGui.QLineEdit(self.tab_6)
        self.sKey.setGeometry(QtCore.QRect(70, 40, 261, 21))
        self.sKey.setObjectName(_fromUtf8("sKey"))
        self.label_2 = QtGui.QLabel(self.tab_6)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 61, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btnCertificate = QtGui.QPushButton(self.tab_6)
        self.btnCertificate.setGeometry(QtCore.QRect(340, 10, 41, 21))
        self.btnCertificate.setObjectName(_fromUtf8("btnCertificate"))
        self.btnKey = QtGui.QPushButton(self.tab_6)
        self.btnKey.setGeometry(QtCore.QRect(340, 40, 41, 21))
        self.btnKey.setObjectName(_fromUtf8("btnKey"))
        self.chkIsTLSControlRequired = QtGui.QCheckBox(self.tab_6)
        self.chkIsTLSControlRequired.setGeometry(QtCore.QRect(70, 70, 161, 22))
        self.chkIsTLSControlRequired.setObjectName(_fromUtf8("chkIsTLSControlRequired"))
        self.chkIsTLSDataRequired = QtGui.QCheckBox(self.tab_6)
        self.chkIsTLSDataRequired.setGeometry(QtCore.QRect(70, 100, 161, 22))
        self.chkIsTLSDataRequired.setObjectName(_fromUtf8("chkIsTLSDataRequired"))
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setGeometry(QtCore.QRect(20, 10, 701, 17))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.rdbUnix = QtGui.QRadioButton(self.tab_7)
        self.rdbUnix.setGeometry(QtCore.QRect(100, 30, 51, 22))
        self.rdbUnix.setObjectName(_fromUtf8("rdbUnix"))
        self.rdbDummy = QtGui.QRadioButton(self.tab_7)
        self.rdbDummy.setGeometry(QtCore.QRect(20, 30, 71, 22))
        self.rdbDummy.setObjectName(_fromUtf8("rdbDummy"))
        self.groupBoxDummy = QtGui.QGroupBox(self.tab_7)
        self.groupBoxDummy.setGeometry(QtCore.QRect(10, 70, 701, 281))
        self.groupBoxDummy.setObjectName(_fromUtf8("groupBoxDummy"))
        self.chkAnonumous = QtGui.QCheckBox(self.groupBoxDummy)
        self.chkAnonumous.setGeometry(QtCore.QRect(10, 20, 161, 22))
        self.chkAnonumous.setObjectName(_fromUtf8("chkAnonumous"))
        self.sAnonymousHomeDir = QtGui.QLineEdit(self.groupBoxDummy)
        self.sAnonymousHomeDir.setGeometry(QtCore.QRect(340, 20, 113, 21))
        self.sAnonymousHomeDir.setObjectName(_fromUtf8("sAnonymousHomeDir"))
        self.label_20 = QtGui.QLabel(self.groupBoxDummy)
        self.label_20.setGeometry(QtCore.QRect(170, 20, 161, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.btnAnonymousHomeDir = QtGui.QPushButton(self.groupBoxDummy)
        self.btnAnonymousHomeDir.setGeometry(QtCore.QRect(460, 20, 41, 27))
        self.btnAnonymousHomeDir.setObjectName(_fromUtf8("btnAnonymousHomeDir"))
        self.sPassword = QtGui.QLineEdit(self.groupBoxDummy)
        self.sPassword.setGeometry(QtCore.QRect(200, 100, 113, 21))
        self.sPassword.setObjectName(_fromUtf8("sPassword"))
        self.label_31 = QtGui.QLabel(self.groupBoxDummy)
        self.label_31.setGeometry(QtCore.QRect(130, 190, 91, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_27 = QtGui.QLabel(self.groupBoxDummy)
        self.label_27.setGeometry(QtCore.QRect(130, 70, 61, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.sHome = QtGui.QLineEdit(self.groupBoxDummy)
        self.sHome.setGeometry(QtCore.QRect(200, 130, 113, 21))
        self.sHome.setObjectName(_fromUtf8("sHome"))
        self.sMsgLogin = QtGui.QLineEdit(self.groupBoxDummy)
        self.sMsgLogin.setGeometry(QtCore.QRect(230, 160, 113, 21))
        self.sMsgLogin.setObjectName(_fromUtf8("sMsgLogin"))
        self.label_29 = QtGui.QLabel(self.groupBoxDummy)
        self.label_29.setGeometry(QtCore.QRect(130, 130, 61, 17))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_28 = QtGui.QLabel(self.groupBoxDummy)
        self.label_28.setGeometry(QtCore.QRect(130, 100, 61, 17))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_30 = QtGui.QLabel(self.groupBoxDummy)
        self.label_30.setGeometry(QtCore.QRect(130, 160, 91, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.sUsername = QtGui.QLineEdit(self.groupBoxDummy)
        self.sUsername.setGeometry(QtCore.QRect(200, 70, 113, 21))
        self.sUsername.setObjectName(_fromUtf8("sUsername"))
        self.sMsgQuit = QtGui.QLineEdit(self.groupBoxDummy)
        self.sMsgQuit.setGeometry(QtCore.QRect(230, 190, 113, 21))
        self.sMsgQuit.setObjectName(_fromUtf8("sMsgQuit"))
        self.label_26 = QtGui.QLabel(self.groupBoxDummy)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 56, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.btnRemoveUser = QtGui.QPushButton(self.groupBoxDummy)
        self.btnRemoveUser.setGeometry(QtCore.QRect(10, 190, 86, 27))
        self.btnRemoveUser.setObjectName(_fromUtf8("btnRemoveUser"))
        self.groupBoxReadPermissions = QtGui.QGroupBox(self.groupBoxDummy)
        self.groupBoxReadPermissions.setGeometry(QtCore.QRect(400, 50, 301, 91))
        self.groupBoxReadPermissions.setObjectName(_fromUtf8("groupBoxReadPermissions"))
        self.chk_e = QtGui.QCheckBox(self.groupBoxReadPermissions)
        self.chk_e.setGeometry(QtCore.QRect(10, 20, 331, 22))
        self.chk_e.setObjectName(_fromUtf8("chk_e"))
        self.chk_l = QtGui.QCheckBox(self.groupBoxReadPermissions)
        self.chk_l.setGeometry(QtCore.QRect(10, 40, 331, 22))
        self.chk_l.setObjectName(_fromUtf8("chk_l"))
        self.chk_r = QtGui.QCheckBox(self.groupBoxReadPermissions)
        self.chk_r.setGeometry(QtCore.QRect(10, 60, 331, 22))
        self.chk_r.setObjectName(_fromUtf8("chk_r"))
        self.groupBoxWritePermissions = QtGui.QGroupBox(self.groupBoxDummy)
        self.groupBoxWritePermissions.setGeometry(QtCore.QRect(400, 140, 271, 141))
        self.groupBoxWritePermissions.setObjectName(_fromUtf8("groupBoxWritePermissions"))
        self.chk_d = QtGui.QCheckBox(self.groupBoxWritePermissions)
        self.chk_d.setGeometry(QtCore.QRect(10, 40, 331, 22))
        self.chk_d.setObjectName(_fromUtf8("chk_d"))
        self.chk_m = QtGui.QCheckBox(self.groupBoxWritePermissions)
        self.chk_m.setGeometry(QtCore.QRect(10, 80, 331, 22))
        self.chk_m.setObjectName(_fromUtf8("chk_m"))
        self.chk_M = QtGui.QCheckBox(self.groupBoxWritePermissions)
        self.chk_M.setGeometry(QtCore.QRect(10, 120, 261, 21))
        self.chk_M.setObjectName(_fromUtf8("chk_M"))
        self.chk_a = QtGui.QCheckBox(self.groupBoxWritePermissions)
        self.chk_a.setGeometry(QtCore.QRect(10, 20, 331, 22))
        self.chk_a.setObjectName(_fromUtf8("chk_a"))
        self.chk_w = QtGui.QCheckBox(self.groupBoxWritePermissions)
        self.chk_w.setGeometry(QtCore.QRect(10, 100, 331, 22))
        self.chk_w.setObjectName(_fromUtf8("chk_w"))
        self.chk_f = QtGui.QCheckBox(self.groupBoxWritePermissions)
        self.chk_f.setGeometry(QtCore.QRect(10, 60, 331, 22))
        self.chk_f.setObjectName(_fromUtf8("chk_f"))
        self.btnClear = QtGui.QPushButton(self.groupBoxDummy)
        self.btnClear.setGeometry(QtCore.QRect(100, 220, 86, 27))
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.btnApply = QtGui.QPushButton(self.groupBoxDummy)
        self.btnApply.setGeometry(QtCore.QRect(190, 220, 86, 27))
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.btnAdd = QtGui.QPushButton(self.groupBoxDummy)
        self.btnAdd.setGeometry(QtCore.QRect(280, 220, 86, 27))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.btnUserHomeDir = QtGui.QPushButton(self.groupBoxDummy)
        self.btnUserHomeDir.setGeometry(QtCore.QRect(320, 130, 41, 21))
        self.btnUserHomeDir.setObjectName(_fromUtf8("btnUserHomeDir"))
        self.lstUsers = QtGui.QListWidget(self.groupBoxDummy)
        self.lstUsers.setGeometry(QtCore.QRect(10, 70, 101, 111))
        self.lstUsers.setObjectName(_fromUtf8("lstUsers"))
        self.label_36 = QtGui.QLabel(self.tab_7)
        self.label_36.setGeometry(QtCore.QRect(20, 10, 701, 17))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.label_32 = QtGui.QLabel(self.tab_8)
        self.label_32.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.btnLogFile = QtGui.QPushButton(self.tab_8)
        self.btnLogFile.setGeometry(QtCore.QRect(210, 10, 41, 21))
        self.btnLogFile.setObjectName(_fromUtf8("btnLogFile"))
        self.sLogFileName = QtGui.QLineEdit(self.tab_8)
        self.sLogFileName.setGeometry(QtCore.QRect(90, 10, 113, 21))
        self.sLogFileName.setObjectName(_fromUtf8("sLogFileName"))
        self.cmbLevel = QtGui.QComboBox(self.tab_8)
        self.cmbLevel.setGeometry(QtCore.QRect(80, 40, 161, 21))
        self.cmbLevel.setMaxVisibleItems(5)
        self.cmbLevel.setObjectName(_fromUtf8("cmbLevel"))
        self.cmbLevel.addItem(_fromUtf8(""))
        self.cmbLevel.addItem(_fromUtf8(""))
        self.cmbLevel.addItem(_fromUtf8(""))
        self.cmbLevel.addItem(_fromUtf8(""))
        self.cmbLevel.addItem(_fromUtf8(""))
        self.label_33 = QtGui.QLabel(self.tab_8)
        self.label_33.setGeometry(QtCore.QRect(10, 40, 61, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.sLogFileView = QtGui.QPlainTextEdit(self.tab_8)
        self.sLogFileView.setGeometry(QtCore.QRect(10, 70, 721, 311))
        self.sLogFileView.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.sLogFileView.setObjectName(_fromUtf8("sLogFileView"))
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.btnApplyConfig = QtGui.QPushButton(self.centralwidget)
        self.btnApplyConfig.setGeometry(QtCore.QRect(90, 440, 141, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dagobert83-apply-300px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApplyConfig.setIcon(icon1)
        self.btnApplyConfig.setObjectName(_fromUtf8("btnApplyConfig"))
        self.btnStartServer = QtGui.QPushButton(self.centralwidget)
        self.btnStartServer.setGeometry(QtCore.QRect(240, 440, 141, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/spite-lightning-300px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStartServer.setIcon(icon2)
        self.btnStartServer.setObjectName(_fromUtf8("btnStartServer"))
        self.btnCloseAll = QtGui.QPushButton(self.centralwidget)
        self.btnCloseAll.setGeometry(QtCore.QRect(390, 440, 241, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/x-button-300px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCloseAll.setIcon(icon3)
        self.btnCloseAll.setObjectName(_fromUtf8("btnCloseAll"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyFTPD", None))
        self.label_16.setText(_translate("MainWindow", "Server Address", None))
        self.label_17.setText(_translate("MainWindow", "Server Port", None))
        self.rdbNormal.setText(_translate("MainWindow", "Normal", None))
        self.rdbThreaded.setText(_translate("MainWindow", "Threaded", None))
        self.rdbMultiprocess.setText(_translate("MainWindow", "Multiprocess", None))
        self.label_18.setText(_translate("MainWindow", "Maximum Connections", None))
        self.label_19.setText(_translate("MainWindow", "Maximum Connections Per ip", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Server", None))
        self.rdbFTP.setText(_translate("MainWindow", "FTP", None))
        self.rdbThrottled.setText(_translate("MainWindow", "Throttled", None))
        self.rdbDTP.setText(_translate("MainWindow", "DTP", None))
        self.rdbTLS.setText(_translate("MainWindow", "TLS", None))
        self.label_8.setText(_translate("MainWindow", "FTP Timeout", None))
        self.label_9.setText(_translate("MainWindow", "Maximum Loggin Atempts", None))
        self.chkPermitForeignAddresses.setText(_translate("MainWindow", "Permit Foreign Addresses", None))
        self.chkPermitPrivilegedPorts.setText(_translate("MainWindow", "Permit Privileged Ports", None))
        self.label_10.setText(_translate("MainWindow", "Masquerade Address", None))
        self.label_11.setText(_translate("MainWindow", "Start", None))
        self.label_12.setText(_translate("MainWindow", "Stop", None))
        self.label_13.setText(_translate("MainWindow", "Passive Ports Range", None))
        self.chkUseGMTTimes.setText(_translate("MainWindow", "Use GMT Times", None))
        self.chkTCPNoDelay.setText(_translate("MainWindow", "TCP No Delay", None))
        self.chkUseSendFile.setText(_translate("MainWindow", "Use Send File", None))
        self.label_14.setText(_translate("MainWindow", "Auth Failed Timeout", None))
        self.label_15.setText(_translate("MainWindow", "Banner", None))
        self.label_34.setText(_translate("MainWindow", "sec", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "FTP", None))
        self.label_6.setText(_translate("MainWindow", "Write Limit", None))
        self.label_7.setText(_translate("MainWindow", "Read Limit", None))
        self.label_21.setText(_translate("MainWindow", "bytes/sec", None))
        self.label_22.setText(_translate("MainWindow", "bytes/sec", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Throttled", None))
        self.label_3.setText(_translate("MainWindow", "DTP Timeout", None))
        self.label_4.setText(_translate("MainWindow", "In Buffer Size", None))
        self.label_5.setText(_translate("MainWindow", "Out Buffer Size", None))
        self.label_23.setText(_translate("MainWindow", "bytes/sec", None))
        self.label_24.setText(_translate("MainWindow", "bytes/sec", None))
        self.label_25.setText(_translate("MainWindow", "sec", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "DTP", None))
        self.label.setText(_translate("MainWindow", "Certificate", None))
        self.label_2.setText(_translate("MainWindow", "Key File", None))
        self.btnCertificate.setText(_translate("MainWindow", "...", None))
        self.btnKey.setText(_translate("MainWindow", "...", None))
        self.chkIsTLSControlRequired.setText(_translate("MainWindow", "Is TLS Control Required", None))
        self.chkIsTLSDataRequired.setText(_translate("MainWindow", "Is TLS Data Required", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "TLS", None))
        self.label_35.setText(_translate("MainWindow", "Select a handler for the server", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Handlers", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Choose a handler for the server", None))
        self.rdbUnix.setText(_translate("MainWindow", "Unix", None))
        self.rdbDummy.setText(_translate("MainWindow", "Dummy", None))
        self.groupBoxDummy.setTitle(_translate("MainWindow", "Dummy Authorizer", None))
        self.chkAnonumous.setText(_translate("MainWindow", "Set Anonymous Mode", None))
        self.label_20.setText(_translate("MainWindow", "Anonymous Home Directory", None))
        self.btnAnonymousHomeDir.setText(_translate("MainWindow", "...", None))
        self.label_31.setText(_translate("MainWindow", "Quit Message", None))
        self.label_27.setText(_translate("MainWindow", "Username", None))
        self.label_29.setText(_translate("MainWindow", "Home dir", None))
        self.label_28.setText(_translate("MainWindow", "Password", None))
        self.label_30.setText(_translate("MainWindow", "Login Message", None))
        self.label_26.setText(_translate("MainWindow", "Users", None))
        self.btnRemoveUser.setText(_translate("MainWindow", "Remove User", None))
        self.groupBoxReadPermissions.setTitle(_translate("MainWindow", "Read Permissions", None))
        self.chk_e.setText(_translate("MainWindow", "e - change directory (CWD, CDUP)", None))
        self.chk_l.setText(_translate("MainWindow", "l - list files (LIST, NLST, STAT, MLSD, MLST, SIZE)", None))
        self.chk_r.setText(_translate("MainWindow", "r - retrieve file from the server (RETR)", None))
        self.groupBoxWritePermissions.setTitle(_translate("MainWindow", "Write Permissions", None))
        self.chk_d.setText(_translate("MainWindow", "d - delete file or directory (DELE, RMD)", None))
        self.chk_m.setText(_translate("MainWindow", "m - create directory (MKD)", None))
        self.chk_M.setText(_translate("MainWindow", "M - change mode (SITE CHMOD)", None))
        self.chk_a.setText(_translate("MainWindow", "a - append data to an existing file (APPE)", None))
        self.chk_w.setText(_translate("MainWindow", "w - store a file to the server (STOR, STOU)", None))
        self.chk_f.setText(_translate("MainWindow", "f - rename file or directory (RNFR, RNTO)", None))
        self.btnClear.setText(_translate("MainWindow", "Clear", None))
        self.btnApply.setText(_translate("MainWindow", "Apply", None))
        self.btnAdd.setText(_translate("MainWindow", "Add", None))
        self.btnUserHomeDir.setText(_translate("MainWindow", "...", None))
        self.label_36.setText(_translate("MainWindow", "Select Authorizer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Authorizers", None))
        self.label_32.setText(_translate("MainWindow", "Log File Path", None))
        self.btnLogFile.setText(_translate("MainWindow", "...", None))
        self.cmbLevel.setItemText(0, _translate("MainWindow", "INFO", None))
        self.cmbLevel.setItemText(1, _translate("MainWindow", "CRITICAL", None))
        self.cmbLevel.setItemText(2, _translate("MainWindow", "ERROR", None))
        self.cmbLevel.setItemText(3, _translate("MainWindow", "WARNING", None))
        self.cmbLevel.setItemText(4, _translate("MainWindow", "DEBUG", None))
        self.label_33.setText(_translate("MainWindow", "Log Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Logging", None))
        self.btnApplyConfig.setText(_translate("MainWindow", "Apply Configuration", None))
        self.btnStartServer.setText(_translate("MainWindow", "Start Server", None))
        self.btnCloseAll.setText(_translate("MainWindow", "Close Connections And Stop Server", None))

import data_rc
